name: "CodeQL Python Security Scan"

on:
  # Run on every push to main (so that after merge you get scans too)
  push:
    branches: [ main ]

  # Run on pull requests targeting main
  pull_request:
    branches: [ main ]
    types: [opened, reopened, synchronize]

jobs:
  codeql:
    # Only run on PRs coming from a dev/* branch
    if: ${{ github.event_name == 'pull_request' && startsWith(github.head_ref, 'dev/') }}
    name: Analyze Python code with CodeQL
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: python

      - name: Autobuild
        uses: github/codeql-action/autobuild@v2

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
